import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 border-b border-gray-200 dark:border-gray-800">
          {/* Your header content goes here */}
          <nav className="max-w-3xl mx-auto font-semibold">My App Header</nav>
        </header>
        {children}
        <footer className="p-6 border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-600">
          {/* Your footer content goes here */}
          <p>&copy; {new Date().getFullYear()} My Next.js App</p>
        </footer>
      </body>
    </html>
  );
}
